### ISSUE TITLE
How to enter my relationships (my spouse, my parents)?

### ISSUE THREAD

**Issue by minthemiddle** [monicahq/monica#3157] opened 2019-11-03 13:43 UTC
- How do I enter relationships for myself
- I expected this to appear on the relationship tab, but "I" is not a valid contact
- Do I create a contact that is me and relate everything to "me"
- It seems a bit odd to me to treat myself as a regular contact
- This would mean that I get a reminder for my own birthday etc.

**Comment by asbiin** [comment] 2019-11-03 22:46
duplicate of #33

**Closed by asbiin** 2019-11-03 22:46 UTC
