### ISSUE TITLE
I often know the exact birthdate, but not the year

### ISSUE THREAD

**Issue by rickpastoor** [monicahq/monica#573] opened 2017-09-02 19:41 UTC
The title says it all. I don't want to enter an approx number of years or guess the year, because I'll forget that and I then will proceed to congratulate the person with the wrong number of years :)

**Comment by djaiss** [comment] 2017-09-04 16:45
Good one 😀 We'll do it.

**Comment by Silveress** [comment] 2017-09-09 20:01
I just came here to say the same thing, started using a selfhosted  version yesterday and it already came up (a lot of birthdays around me lately)

**Comment by sid3windr** [comment] 2017-09-25 12:15
Heh, also had this one on my "list of things to request". So +1.

**Comment by ghewgill** [comment] 2017-10-10 09:12
Duplicate of #75.

**Comment by djaiss** [comment] 2017-10-22 03:24
You have a good eye @ghewgill  😀

**Closed by djaiss** 2017-10-22 03:24 UTC
Labels: feature request
