### ISSUE TITLE
Ubuntu installation results in php file in plain text

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#2445] opened 2019-02-15 14:25 UTC
After following the installation instructions [here](https://github.com/monicahq/monica/blob/master/docs/installation/ubuntu.md) (which I've updated last year and used to work), I'm now getting the following in the main page of the application - this is obviously PHP code in plain text:
```
<?php

/**
 * Laravel - A PHP Framework For Web Artisans.
 *
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 */

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels nice to relax.
|
*/

require __DIR__.'/../bootstrap/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);
```

I'm thinking this has something to do with the Apache-PHP configuration. Any thoughts?

**Comment by tomgs** [comment] 2019-02-15 14:30
Also, tried installing `libapache2-mod-php` and now I get the following page:

![whoops__something_went_wrong_](https://user-images.githubusercontent.com/8835035/52862870-f59dbe80-313e-11e9-8b8b-e29c82062729.png)

That says:

`could not find driver (SQL: select * from `cache` where `key` = laravel_cachecloudflare.proxies limit 1)`

If it's hard to read.

**Comment by asbiin** [comment] 2019-02-15 23:10
Duplicate of #2320

**Comment by wcypierre** [comment] 2019-02-20 14:33
@tomgs in case that you're still looking for a solution, I've posted a solution on #2320

**Comment by tomgs** [comment] 2019-02-20 14:37
I am indeed! Thank you so much for this.

**Closed** 2019-02-24 14:59 UTC
