### ISSUE TITLE
remove contacts duplicates

### ISSUE THREAD

**Issue by alexriabtsev** [monicahq/monica#3054] opened 2019-10-01 10:58 UTC
Monica doesn't have contacts duplicates feature which is essential as I'm importing hundreds of contacts from different sources (Google Contacts, LinkedIn, Facebook, emails...).

**Describe the solution you'd like**
I'd like to be able to see and merge duplicates inside monica.

**Describe alternatives you've considered (optional)**
Now I'm using Google Contacts to dedup my contacts but it's not a solution as it works only with Google Contacts but monica would keep all my contacts.

**Comment by asbiin** [comment] 2019-10-03 02:05
Hi. I think this is quite the same as #1687 right?

**Comment by alexriabtsev** [comment] 2019-10-03 05:39
exactly! merge my feature request and please do it ;)

**Comment by asbiin** [comment] 2019-10-20 16:21
duplicate of #1687

**Comment by asbiin** [comment] 2019-10-20 16:22
@alexriabtsev thanks. Don't hesitate to participate too ;)

**Closed by asbiin** 2019-10-20 16:21 UTC

**Comment by alexriabtsev** [comment] 2019-10-21 16:51
> @alexriabtsev thanks. Don't hesitate to contribute too ;)

I'm not developer unfortunately
