### ISSUE TITLE
Caldav birthdays subscription won't work in nextcloud

### ISSUE THREAD

**Issue by Thormus** [monicahq/monica#6821] opened 2023-08-25 16:01 UTC
I am attempting to expose birthdays to my nextcloud calendar using the link provided in monica.

https://my.domain/dav/calendars/my.email@gmail.com/birthdays

I am unable to utilize this subscription in ios as well. 

I have added this in my config for nginxproxymanager

`location ~ /\.well-known/(?:carddav|caldav) {
    return 301 https://$host/dav;
  }`

Is there anything I need to be doing to allow birthdays to be exposed without being able to authenticate with monica in any way?

**Comment by asbiin** [comment] 2023-10-31 09:44
duplicate of #1444

**Closed by asbiin** 2023-10-31 09:44 UTC
