### ISSUE TITLE
Some links in docker version redirect to localhost despite APP_URL set to custom domain

### ISSUE THREAD

**Issue by ethanquix** [monicahq/monica#1386] opened 2018-05-24 12:05 UTC
**Describe the bug**
The docker version of Monica has a lot of links which redirect to localhost and not the custom URL.
Example,
- The 'add someone' button redirect to 'my_custom_domain.com/people/add'
- The 'contact' button in the contact list redirect to 'localhost:MY_PORT/people/h:XXXXXX'

**Which version are you using:**
- Latest docker image taken from the docker hub with docker.compose set as said in the wiki

**Comment by g-goessel** [comment] 2018-07-30 13:20
Do you use a reverse proxy ?
I had the same issue (except that _every_ link was redirecting to localhost) and fixing my nginx reverse proxy config solved the issue.

For those interested :
```
    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://localhost:3000;
    }
```

**Comment by fabwu** [comment] 2018-09-07 22:01
I can confirm that this is an issue with the reverse proxy. I added the headers above and the problem was resolved.

@djaiss I think you can close this issue.

**Closed** 2019-05-07 23:16 UTC
Labels: docker
