### ISSUE TITLE
Disallow to create empty tags

### ISSUE THREAD

**Issue by edi9999** [monicahq/monica#6235] opened 2022-07-20 12:58 UTC
By going to the following page (the page of one person)

http://localhost:9090/people/h:9qyA7LJYWZ18mVavMj

When adding a tag (for example "a"), if you type enter multiple times, it creates as many empty tags as the number of keypresses.

Here is a screenshot of what it results in : 

![Selection_002](https://user-images.githubusercontent.com/2071336/179987700-70b660b3-253f-4600-96cc-723a62551937.png)

This bugs seems to happen only after entering one tag that is not an empty string.

**Comment by edi9999** [comment] 2022-07-20 12:58
Also, after reloading the page, those empty tags disappear, so it seems that this bug is only in the UI

**Comment by particleflux** [comment] 2022-09-06 20:53
Can reproduce locally, seems to be a regression bug. Fixed in #6314

**Closed** 2022-10-16 09:53 UTC

**Comment by edi9999** [comment] 2022-10-17 10:04
Thanks !
