### ISSUE TITLE
import from google vcf fails

### ISSUE THREAD

**Issue by bbrendon** [monicahq/monica#3369] opened 2019-12-27 06:25 UTC
**Describe the bug**
Import works up until a point in the vcf and then fails. Deleting the contact from the vcf and restarting the import will cause it to continue. I'm tried cleaning up the vcf and reimported about 8 times now and I've only got about 100 contacts imported. It's very tedious.

I'm using the docker version. Right now I'm just pointing to the IP:port of the container and not using https.

I set the docker env to debug and I get the output below after clicking upload.

```

(1/1) NotReadableExceptionUnable to init from given binary data.
--
in Decoder.php line 115
at Decoder->initFromBinary('��i��凘(� ^�ǫr��z{\\�o�"Z�f�' . "\0" . '���Y⾛�#�' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '��^��eP��5���8(b��m�ƀ' . "\0" . '�@!' . "\0" . '�a��#�')in AbstractDecoder.php line 327
at AbstractDecoder->init('��i��凘(� ^�ǫr��z{\\�o�"Z�f�' . "\0" . '���Y⾛�#�' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '��^��eP��5���8(b��m�ƀ' . "\0" . '�@!' . "\0" . '�a��#�')in AbstractDriver.php line 66
at AbstractDriver->init('��i��凘(� ^�ǫr��z{\\�o�"Z�f�' . "\0" . '���Y⾛�#�' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '��^��eP��5���8(b��m�ƀ' . "\0" . '�@!' . "\0" . '�a��#�')in ImageManager.php line 54
at ImageManager->make('��i��凘(� ^�ǫr��z{\\�o�"Z�f�' . "\0" . '���Y⾛�#�' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '��^��eP��5���8(b��m�ƀ' . "\0" . '�@!' . "\0" . '�a��#�')in Facade.php line 239
at Facade::__callStatic('make', array('��i��凘(� ^�ǫr��z{\\�o�"Z�f�' . "\0" . '���Y⾛�#�' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '��^��eP��5���8(b��m�ƀ' . "\0" . '�@!' . "\0" . '�a��#�'))in UploadPhoto.php line 89
at UploadPhoto->importFile(array('account_id' => 1, 'data' => '��i��凘(� ^�ǫr��z{\\�o�"Z�f�' . "\0" . '���Y⾛�#�' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '��^��eP��5���8(b��m�ƀ' . "\0" . '�@!' . "\0" . '�a��#�'))in UploadPhoto.php line 55
at UploadPhoto->execute(array('account_id' => 1, 'data' => '��i��凘(� ^�ǫr��z{\\�o�"Z�f�' . "\0" . '���Y⾛�#�' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '��^��eP��5���8(b��m�ƀ' . "\0" . '�@!' . "\0" . '�a��#�'))in ImportVCard.php line 636
at ImportVCard->importPhoto(object(Contact), object(VCard))in ImportVCard.php line 447



```

**Comment by bbrendon** [comment] 2019-12-27 07:11
After toying around a bit I finally discovered it's the `PHOTO:` like breaking it.

e.g.

```
PHOTO:https://lh6.googleusercontent.com/-7nFWS-didog/WAWPiKpwebI/AAAAAAAAAA
 A/v20VS2xQn0YF5XF734FY0baps27k34QZACOQCEAE/photo.jpg
```

**Comment by asbiin** [comment] 2019-12-27 09:09
duplicate of #3352

**Closed by asbiin** 2019-12-27 09:09 UTC
