### ISSUE TITLE
Add "Items borrowed" feature

### ISSUE THREAD

**Issue by mgrhm** [monicahq/monica#5309] opened 2021-06-25 13:00 UTC
You can currently (mis)use "Debts" to do this, but it's not great and it would be better if there was a specific feature for it.

Even better would be the option to add timed reminders about the item borrowed ("Remind me in 45 days to return Iain’s _Harry Potter_").

**Comment by asbiin** [comment] 2021-06-27 13:35
IMHO this is a duplicate of #1706

**Closed by asbiin** 2021-06-27 13:35 UTC

**Comment by mgrhm** [comment] 2021-06-27 13:45
Sorry -- completely slipped my mind that #1706 existed and that I'd liked it.
