### ISSUE TITLE
Very slow to render /people view of many contacts

### ISSUE THREAD

**Issue by nemik** [monicahq/monica#345] opened 2017-06-17 19:44 UTC
Hello,

First thank you for making this wonderful application, I really wanted something like this for a long time.

I installed everything on my local server and imported the .vcf contacts from my Gmail account. I first exported them using this guide: http://www.akruto.com/backup-phone-contacts-calendar/how-to-export-google-contacts-to-csv-or-vcard/
then imported them as per the readme. This resulted in about 2000 contacts being added to Monica.

When I visit the `/people` URL, it takes 161 seconds to show! I actually had to increase the PHP and nginx timeouts to even get it to load, because it was otherwise timing out. The MySQL queries are very quick for this action, but it seems rendering them takes a very long time.

Also, the view is not paginated, so all 2000 show on the same page. Maybe this is something that should be fixed.

I can try to make a pull request for this but have not used PHP for many years and will take me time to figure out Laravel.

Anyway just wanted to bring this issue to your attention and thank you again for taking the time and effort to make this application.

**Comment by Phrohdoh** [comment] 2017-06-17 20:48
Hi @nemik!

~2.7 minutes is a very long time indeed!

Perhaps https://stackoverflow.com/a/30298599/3816796 and https://laravel.com/docs/5.4/pagination will be of help for whomever decides to implement contact pagination.

**Comment by Nebucatnetzer** [comment] 2017-06-17 21:40
I agree that the /people view takes very long to load. It doesn't take 2.7 minutes but still quite some time.
Especially since I only have ~70 contact without any profile pictures.

**Comment by djaiss** [comment] 2017-06-18 00:35
Oh wow. Definitely didn't expect to store 2000 contacts in one user account. We can something about this. Paginating will be a first step towards this. I'll submit a patch in the coming days.

**Comment by djaiss** [comment] 2017-06-18 00:37
On a sidenote, paginating will affect the search on the contact list page. Currently, it only searches the table below it, and doesn't do any AJAX. Therefore, we'll need to change how the search works. By the way, we also need to add a search box in the header, but this is another issue.

**Comment by yamakadi** [comment] 2017-06-18 13:13
Even with about 5000 contacts, it only takes 8 seconds on my server at most.

**Comment by djaiss** [comment] 2017-06-18 22:32
Yeah it's definitely not right that it takes that long. It should be pretty fast.

**Comment by nemik** [comment] 2017-06-18 23:07
In the debug console, the 4 MySQL queries all finish in about 60ms
combined, so it's definitely not any bottleneck on the DB. The time seems
to be in the rendering. I'm running this on an i5 with 16GB of RAM. Ubuntu
16, php7.0 , and nginx.

**Comment by zach2825** [comment] 2017-06-24 17:31
Even after the query has gotten the results its taking the view a long time to render. It appears to be caused by the kid count. on each row its running a count on the kids. In my testing, if i remove that count it loads pretty quickly. Has anybody else experienced that?

**Comment by Nebucatnetzer** [comment] 2017-06-25 09:46
@zach2825 can you explain to me how to remove the counter so I can give it a try?

**Comment by djaiss** [comment] 2017-06-30 03:26
I've found the issue. It'll be fixed here: https://github.com/monicahq/monica/pull/415

**Comment by djaiss** [comment] 2017-06-30 03:28
Fix is in prod. With 500 contacts, in production, it takes ~1 sec to load the page now.

**Closed by djaiss** 2017-06-30 03:28 UTC

**Comment by zach2825** [comment] 2017-06-30 15:19
@Nebucatnetzer im sorry for my slow reply. 

I was wrong. I thought the query to get a count of children was running for each row that potentially it could be thousands of queries to run per page load just to get that count
