### ISSUE TITLE
Ability to forward emails to Monica and link it automatically as a note to a contact

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#414] opened 2017-06-29 16:46 UTC
It would be great to provide, like Basecamp does, a way to forward an email you've just received from a friend to your Monica account.

Monica would automatically check the sender's email address and paste the email as a note in the feed of the right contact.

**Comment by asbiin** [comment] 2019-08-10 21:18
Duplicate of #870

**Closed by asbiin** 2019-08-10 21:18 UTC
Labels: feature request
