### ISSUE TITLE
Selecting multiple participants 

### ISSUE THREAD

**Issue by jatls** [monicahq/monica#2447] opened 2019-02-16 00:31 UTC
Attempting to select multiple participants in an activity redirects to the dashboard upon selecting the new participant’s name.

Self-hosted 2.12.0

**Comment by asbiin** [comment] 2019-02-17 10:11
This is already fixed with #2418, we will release a fix version soon.
Sorry for the problem!

**Comment by SergeAx** [comment] 2019-02-17 21:30
Duplicate of #2327

**Closed** 2019-04-30 21:12 UTC
