### ISSUE TITLE
Parts of the aplication to support @contacts mentioning

### ISSUE THREAD

**Issue by arisAlexis** [monicahq/monica#4647] opened 2020-12-04 22:55 UTC
Many parts of the application could do with mentioning, especially notes and journal entries.

In order to implement this quite a bit of javascript is needed on the page to pull out a similar menu as the search contacts on the toolbar so the user can select the entry which would be converted to the userid beneath and then when pulled out of the database shown as a name. Alternatively the user could just be sure of the exact name to use and @ tag them precisely. Two people with the same name or spelling mistakes would make it break though.

**Comment by asbiin** [comment] 2020-12-12 12:42
This is a duplicate of #829

**Closed by asbiin** 2020-12-12 12:42 UTC
