### ISSUE TITLE
Add participants in activity

### ISSUE THREAD

**Issue by sibuser** [monicahq/monica#347] opened 2017-06-19 09:04 UTC
Would be really good to be able to add participants in the activity so you could later remember who attended this event.

**Comment by djaiss** [comment] 2017-06-19 12:04
Do you mean, adding multiple participants in the same activity instead?

**Comment by sibuser** [comment] 2017-06-19 12:06
Yes. 
For example I met my friend at the party and want to remember who attended this party also so next time you could see the connection.

**Comment by erdmenchen** [comment] 2017-06-19 19:04
Duplicate of #118

**Comment by djaiss** [comment] 2017-06-21 01:25
@erdmenchen Indeed. Closing this one in favour of the other one. Thanks.

**Closed by djaiss** 2017-06-21 01:25 UTC
