### ISSUE TITLE
Birthdays incorrectly stored when manually entered.

### ISSUE THREAD

**Issue by KevinJBoyer** [monicahq/monica#2618] opened 2019-04-19 18:49 UTC
**Describe the bug**
Directly editing the text of a birthday date on the "edit contact information" page, then submitting the form by pressing enter, results in the incorrect date being stored. (Seems like it's usually one day earlier, though on at least one of my contacts it was two days - could have been input error by me in that case, however!)

**Screenshots**
![Screen Shot 2019-04-19 at 2 45 47 PM](https://user-images.githubusercontent.com/31424131/56438714-e3acd900-62b1-11e9-8711-7e9c40913e9c.png)

I click the above form and manually enter the date using the keyboard. I submit the form by pressing the enter key on the keyboard. I haven't tried to replicate under other conditions.

![Screen Shot 2019-04-19 at 2 46 01 PM](https://user-images.githubusercontent.com/31424131/56438715-e3acd900-62b1-11e9-9330-c4bc5204b7ac.png)

This is the result. Note that I typed in May 26 but the stored date is May 25.

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Additional context**
Chrome 73.0.3683.103 on MacOS Mojave

**Comment by jflatz** [comment] 2019-04-20 13:16
Duplicate of [2513](https://github.com/monicahq/monica/issues/2513)

**Comment by KevinJBoyer** [comment] 2019-04-20 13:50
So it is! Thanks for catching. What's the correct procedure here - for me to just close this?

**Comment by jflatz** [comment] 2019-04-21 18:47
Not sure if you can close it your self. Likely @asbiin  or @djaiss will close it when they are available.

**Closed** 2019-04-21 20:42 UTC
