### ISSUE TITLE
Date widget sets date to one day before

### ISSUE THREAD

**Issue by mrzv** [monicahq/monica#2513] opened 2019-03-11 00:28 UTC
**Describe the bug**
When filling the date manually (e.g., when entering somebody's birthday), the date in the calendar popup widget gets set to one day before what's actually entered. When submitting, it's the widget date that gets recorded. If one doesn't catch this, one gets lots of birthdays shifted by one day.

**Which version are you using:**
Self-hosted 2.12.1

**Comment by asbiin** [comment] 2019-03-13 20:43
I cannot reproduce this.
What is your locale and timezone?

**Comment by mrzv** [comment] 2019-03-13 20:49
Both client and server are set to Pacific. But I think this is entirely a client-side UI issue. Because even as I enter a given date, the date before it is highlighted in the calendar widget. The client is a Mac, using Chrome, if that helps.

**Comment by tbirrell** [comment] 2019-03-18 00:05
I'm running into the same issue. I'll set to March 31st and it'll display as March 30th (and if, as in the case of birthdays, I set a reminder, it is also off by a day). Then when I go in to edit it, it says March 30th. Upon saving _again_ it stays. I haven't been able to look into it yet, but I suspect that somewhere between PHP and the DB, a timezone conversion is breaking something.

I'm on version 2.12.0

**Comment by tbirrell** [comment] 2019-03-26 23:45
Further exploration shows that this is a discrepancy with the Vue Datepicker. If you use the popup to select the date, it is correct. If you type it in, it will actually show the previous date in the popup, then send that (incorrect) date back to the PHP.

**Comment by asbiin** [comment] 2019-05-07 07:53
This is fixed by #2655

**Closed by asbiin** 2019-05-07 07:53 UTC
