### ISSUE TITLE
Birthdays do not show on the Dashboard on the actual birth day,  Perhaps a 'less than' should be 'less than or equal to'?  v2.17 pulled from master today.  Has been an issue for several months.

### ISSUE THREAD

**Issue by daryljones** [monicahq/monica#3740] opened 2020-03-24 22:18 UTC
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
A clear and concise description of what the bug is. If your comment is `it doesn't work`, we won't know what to do with it.

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.
**Which version are you using:**
 - Hosting version on https://app.monicahq.com
 - Mobile version
 - A server you maintain yourself (if so, please indicate your current version of Monica)

**Additional context**

**Comment by asbiin** [comment] 2020-04-11 20:09
Just a point: that's not as simple as a 'less than or equal to' ...

**Comment by asbiin** [comment] 2020-04-26 21:43
Duplicate of #839

**Closed by asbiin** 2020-04-26 21:44 UTC
Labels: feature request
