### ISSUE TITLE
Back-Up Codes for Two-Factor Authentication

### ISSUE THREAD

**Issue by stephenjudge** [monicahq/monica#1219] opened 2018-04-26 21:44 UTC
It is common practice in most 2FA implementations to have a set of printable backup codes that can be used in the event you loose your 2FA device. When I activated 2FA on Monica I was disappointed to see there was no facility for backup codes offered. Please implement this.

**Comment by asbiin** [comment] 2018-04-26 21:56
Thank you for you concern. However, this is already plan, this issue is a duplicate of #824

**Closed by asbiin** 2018-04-26 21:56 UTC
