### ISSUE TITLE
Make phone number, tags and other profile information searchable

### ISSUE THREAD

**Issue by b3nd1k** [monicahq/monica#5772] opened 2021-12-19 15:08 UTC
Hey! If I go to the "Search your contact" field at the top, I am only able to search for names. I should be able to search by phone number, email, tags. Go even further and create a smart search where I can say "People I have contacted in the last 7 days".

**Comment by asbiin** [comment] 2021-12-27 23:25
duplicate of #3515

**Closed by asbiin** 2021-12-27 23:25 UTC
