### ISSUE TITLE
compact with undefined variable breaks on PHP 7.3 while editing contacts

### ISSUE THREAD

**Issue by 4khi1** [monicahq/monica#3596] opened 2020-02-18 08:52 UTC
![image](https://user-images.githubusercontent.com/21128035/74719405-f7222b00-5259-11ea-9030-4fe687348bd1.png)

**Comment by 4khi1** [comment] 2020-02-18 08:53
Duplicate of https://github.com/laravel/framework/issues/26936

**Comment by 4khi1** [comment] 2020-02-18 08:54
Fixed by downgrading PHP version to 7.1

**Comment by 4khi1** [comment] 2020-02-18 08:55
Documentation needs to be updated #Requirements  -  PHP Version

**Comment by asbiin** [comment] 2020-02-19 06:35
Thank you for this feedback.

> Documentation needs to be updated #Requirements - PHP Version

Well, no, we support php 7.3.
If there is a problem with Laravel, it should be fixed in Laravel.

What page/action did you do to have this error?

**Comment by 4khi1** [comment] 2020-02-19 06:44
![image](https://user-images.githubusercontent.com/21128035/74808670-5ee77d00-5311-11ea-8084-fd89bdc7b983.png)


After submit... it's giving the error

**Comment by asbiin** [comment] 2020-02-29 15:22
I cannot reproduce this bug.
I'm sure you don't have the last version of Monica. Please upgrade first.

**Closed by asbiin** 2020-02-29 15:22 UTC
