### ISSUE TITLE
[Docker] storage/logs/laravel.log cannot be written by web process

### ISSUE THREAD

**Issue by kidk** [monicahq/monica#570] opened 2017-08-30 15:59 UTC
On a fresh docker container of monica the environment is complaining that  storage/logs/laravel.log cannot be written to. A quick `chmod 777  storage/logs/laravel.log` fixes the issue. 

I think the `storage/logs/laravel.log` file needs to be removed for Docker builds or add the chmod command to the Dockerfile. 

If you agree I can create a pull request for this.

**Comment by djaiss** [comment] 2017-09-01 00:28
Thanks. The problem is that I'm really not familiar with Docker at all, so I don't know if this change will be actually beneficial. It would be awesome if the community could answer this question better than I could.

**Comment by kidk** [comment] 2017-09-01 07:48
I'll create a pull request with the commands to make all the dirs writeable that are used in the laravel deployer task. (https://github.com/deployphp/deployer/blob/master/recipe/laravel.php) I assume they have the right information. I will see what the community says, but then at least we have some changes to look at.

Thanks for the great project by the way. I hope to contribute some code in the future when I have the time.

**Comment by gnumoksha** [comment] 2017-10-18 22:23
Please, see https://github.com/laravel/internals/issues/126

**Comment by djaiss** [comment] 2017-12-14 14:04
I don't know if this issue was solved. I'll close it, let me know if it needs to be reopened.

**Closed by djaiss** 2017-12-14 14:04 UTC
Labels: packaging

**Comment by aiveras** [comment] 2019-06-19 10:49
In the new version 2.14 the problem is again present

**Comment by ruubje11** [comment] 2019-06-20 11:56
Present for me too.
