### ISSUE TITLE
Dashboard Yearly Reminders should persist on day of event.

### ISSUE THREAD

**Issue by mikekay1** [monicahq/monica#5696] opened 2021-11-11 15:38 UTC
Hello and thanks for the great app,

This one is fairly simple, mark it bold or make it red or something when looking at the dashboard on the day of an event.

Example being: Today is Nov 11 and its my friends birthday. But looking at the dashboard it is already gone. I usually enter the app and look at a glance some sort of bold visual reminder would be one more flag to me saying, text them -- today is the day.

Let me know if you need more info!

**Comment by asbiin** [comment] 2021-11-15 20:52
Thank you
actually this is a duplicate of #839

**Closed by asbiin** 2021-11-15 20:52 UTC

**Comment by mikekay1** [comment] 2021-11-15 20:56
Ahhh ok! Np thanks for making a sweet app!
