### ISSUE TITLE
Missing text in success message after adding new note

### ISSUE THREAD

**Issue by rickpastoor** [monicahq/monica#379] opened 2017-06-23 07:14 UTC
* Add a new note to a person
* You'll see this message:

<img width="273" alt="schermafbeelding 2017-06-23 om 09 12 31" src="https://user-images.githubusercontent.com/149958/27470462-466500c4-57f4-11e7-8124-40dea5e03fe5.png">

**Comment by ghewgill** [comment] 2017-06-23 10:01
Duplicate of #338

**Closed** 2017-07-07 12:16 UTC

**Comment by rickpastoor** [comment] 2017-07-07 14:16
🎉
