### ISSUE TITLE
Base table or view not found: 1146 Table 'premc_premc_information_schema.tables' doesn't exist

### ISSUE THREAD

**Issue by GaneshKandu** [monicahq/monica#2501] opened 2019-03-07 11:57 UTC
Hi,

Getting Error while exporting "Export your account data" from  ```Dashboard > Settings > Export >Export to SQL```

```

Whoops! Something went wrong.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'premc_premc_information_schema.tables' doesn't exist (SQL: select `table_name` from `premc_premc_information_schema`.`tables` where `table_schema` = monica2120)

Back to homepage
```
installed with custom table prefix

[laravel-2019-03-07.log](https://github.com/monicahq/monica/files/2941086/laravel-2019-03-07.log)

**Comment by asbiin** [comment] 2019-05-17 04:28
It might be related to #2321

**Comment by asbiin** [comment] 2019-05-17 04:50
Duplicate of #1896

**Closed** 2019-08-09 12:54 UTC
Labels: bug
