### ISSUE TITLE
Relax requirement that birth date be after 6/6/1967

### ISSUE THREAD

**Issue by rosstex** [monicahq/monica#55] opened 2017-06-06 22:16 UTC
Would like to use this for my parents/grandparents, but they're too old for this date. Thanks!

**Comment by ocdtrekkie** [comment] 2017-06-06 22:32
Duplicate of #16 and should be fixed by https://github.com/monicahq/monica/commit/e9a776ca285f78dadd28e1c2a73a250fc61f03af

**Comment by djaiss** [comment] 2017-06-07 00:24
This is now fixed and in production. Sorry for the troubles.

**Closed by djaiss** 2017-06-07 00:24 UTC
