### ISSUE TITLE
Facebook OAuth broken

### ISSUE THREAD

**Issue by ChuckQuinnIV** [monicahq/monica#40] opened 2017-06-06 19:07 UTC
Happens on every Facebook authentication link on https://monicahq.com/

**Comment by djaiss** [comment] 2017-06-07 01:21
I disabled the Facebook login entirely until this is fixed. Sorry about that.

**Comment by djaiss** [comment] 2017-06-08 21:05
Duplicate of #39

**Closed by djaiss** 2017-06-08 21:05 UTC
