### ISSUE TITLE
Updating preferences functionality does not work

### ISSUE THREAD

**Issue by PetarMI** [monicahq/monica#3826] opened 2020-04-12 12:08 UTC
**Describe the bug**
Whenever I press `Update preferences` under `Account settings` and error pops up. Please refer to the screenshot below. 

**Screenshots**

![image](https://user-images.githubusercontent.com/3933632/79068405-e5dc2480-7cc6-11ea-8aa0-ce07f6ffafb8.png)

**Which version are you using:**
Using the docker-compose Apache version under a Windows 10 host. `docker-compose` file points to `image: monicahq/monicahq`.

**Comment by asbiin** [comment] 2020-04-12 14:01
duplicate of #3748

**Comment by asbiin** [comment] 2020-04-12 14:02
This is already fixed by #3792

**Closed by asbiin** 2020-04-12 14:01 UTC
