### ISSUE TITLE
Mobile view of new dashboard is broken

### ISSUE THREAD

**Issue by erdmenchen** [monicahq/monica#792] opened 2018-01-11 12:57 UTC
The new dashboard design (released with version 1.6.0) is not only not mobile friendly, but also breaks the layout:

![monica - broken mobile dashboard]()

Issues:
* Avatars are overflowing (and too big)
* Avatars with profile pictures are not shown
* Misplaced "Add someone" button
* Content layout is too narrow for 2 column setup (see statistics container) -> would be better to use single column setup for mobile view

**Comment by tbirrell** [comment] 2018-02-09 18:32
I also have experienced this. On the iPhone SE it doesn't try to do two columns, but it is still very broken.

**Comment by jarradh** [comment] 2018-05-09 08:03
+1 mobile layout is broken, i want to use Monica on the go 90% of the time

**Comment by pqhf5kd** [comment] 2019-01-22 13:48
This is still an issue on Monica Version: 2.11.2 and Safari 12.0.1

**Comment by Bounz** [comment] 2019-01-27 13:11
Hi @djaiss.
As the problem is still there I dug a little bit and it seems that the problem is around flexbox (without wrap) with last consulted contacts.
Here are some screenshots.
iPhone:
![actual_iphone](https://user-images.githubusercontent.com/3062744/51801244-3dba7700-224c-11e9-82b6-56fcdb501bbf.png)

iPhone (the page scrolls horizontally 😥 ):
![actual_iphone2](https://user-images.githubusercontent.com/3062744/51801249-41e69480-224c-11e9-9ef6-312762f16b17.png)

iPad
![actual_ipad](https://user-images.githubusercontent.com/3062744/51801263-56c32800-224c-11e9-891e-de564122d6de.png)

iPad (landscape):
![actual_ipad_landscape](https://user-images.githubusercontent.com/3062744/51801270-60e52680-224c-11e9-9c73-c7cc32923d99.png)

I spent a couple of hours playing with the layout and trying to show all last consulted contacts, but there were problems with a unification of the layout between mobile, tablet and desktop.
Finally, I propose to abandon flexbox and replace it with div with `overflow: hidden` and make avatars a floatable divs. And also organize "Last consulted" block in one column on mobiles. This will result in following:
iPhone:
![proposed_iphone](https://user-images.githubusercontent.com/3062744/51801310-000a1e00-224d-11e9-90eb-bc0cd302471b.png)

iPad:
![proposed_ipad](https://user-images.githubusercontent.com/3062744/51801315-0b5d4980-224d-11e9-94f8-8499d3e4ecb2.png)

iPad (landscape):
![proposed_ipad_landscape](https://user-images.githubusercontent.com/3062744/51801316-17490b80-224d-11e9-90a2-e8ad62349c85.png)

Also, this solution fixes the issue with squeezed avatar images.
What do you think about this?

**Comment by igbanam** [comment] 2019-01-30 19:04
I'm experiencing this too. I think the fix from @Bounz may just do it

**Comment by asbiin** [comment] 2019-02-09 14:49
Fixed by #2374

**Closed by asbiin** 2019-02-09 14:49 UTC
Labels: bug
