### ISSUE TITLE
Auto-select "I know the exact birthdate of this person, which is" when date input is focused

### ISSUE THREAD

**Issue by TheActualWalko** [monicahq/monica#21] opened 2017-06-06 17:37 UTC

**Comment by sid3windr** [comment] 2017-06-17 16:37
Some more rationale about why to do this is in #341 (which I closed as it was effectively a dupe of this issue).

**Comment by djaiss** [comment] 2017-07-09 22:45
Thanks for the suggestion. It's now in production!

**Comment by sid3windr** [comment] 2017-08-23 22:16
This is either broken again, or not fully functional... Creating a contact still does not auto-refocus the radio button, losing birthday information.

**Comment by asbiin** [comment] 2019-05-05 11:47
UI has changed

**Closed by asbiin** 2019-05-05 11:47 UTC
Labels: enhancement
