### ISSUE TITLE
Unable to Update Activites and Other Fields after Upgrade 2.16.0 to 2.17.0

### ISSUE THREAD

**Issue by nosbig** [monicahq/monica#3780] opened 2020-04-01 00:17 UTC
Activities were added while system was 2.16.0.  After upgrade to 2.17.0, activities no longer show in the detail page for the contact.  Database still has data in the 'activities' table, but the information is not visible in the application.

I am self-hosting on personal VPS.

**Comment by nosbig** [comment] 2020-04-01 02:35
Attempted to add a new event from the 2.17.0 release, and I received an error:
```
Whoops! Something went wrong.

Key path: "file:///var/www/html/monica/storage/oauth-public.key" 
does not exist or is not readable

```

My first step was to check the filesystem for the presence of the file as well as permissions.  I learned that the file did not exist at this time; I haven't yet checked my backups to confirm whether it existed prior to the upgrade.  I would assume that it did, based on what I have read so far.

Not being a strong PHP developer, I did a quick search on Google for the error message, and I found several threads the pointed this to being an issue with the Laravel framework and not having Passport installed.

Since the file didn't exist, I followed the recommendation of the threads to execute:
`php artisan passport:install`

This generated "oauth-private.key" and "oauth-public.key".  Then, I refreshed the web interface and visited a contact which previously had an associated activity.  The activities are now visible.  I have also been able to create, edit, and delete activities.

My original problem appears to be resolved, but I don't know if this is a known or consistent problem when upgrading from an earlier version to 2.17.0.

As an aside, I also tried the new "associate a contact as me" feature with no success prior to this fix.  When I went to preferences and pulled up the "Select a contact" dialog, I could choose my own record, but then the application would refuse to save the selection.  Now that I rebuilt the oauth keys, I was immediately able to save the selection as expected.

I am updating the issue title to reflect that this has/had a larger scope than just activities not being visible on a contact's view.

**Comment by nosbig** [comment] 2020-04-01 03:28
I have been able to review my backups to confirm that the keys did not exist in my 2.16.0 installation; perhaps one of the composer dependencies didn't complete that step or it needs added to the upgrade steps?

**Comment by nosbig** [comment] 2020-04-03 23:18
As mentioned in the duplicate issue #3790, the Apache process needs restarted after this process.  This can either be a service restart or a system reboot.  I forgot that I had done so as well.

**Comment by asbiin** [comment] 2020-04-07 17:57
This is a duplicate of #3442

**Comment by asbiin** [comment] 2020-04-11 19:42
See #3816
Running `setup:production` or `monica:update` now creates required the encryption keys and personal access client.

**Closed by asbiin** 2020-04-11 19:42 UTC
