### ISSUE TITLE
HTTP 500 on Every Request After Enabling 2FA

### ISSUE THREAD

**Issue by Mohammed90** [monicahq/monica#2832] opened 2019-07-12 21:49 UTC
**Describe the bug**

Nothing happens in UI when I click the `Get recovery codes` button. I checked the console and the response is HTTP 500 with the body:
```json
{
    "message": "The payload is invalid."
}
```

**Screenshots**
N/A

**Which version are you using:**
 - A server you maintain yourself (if so, please indicate your current version of Monica): v2.14.0

**Comment by Mohammed90** [comment] 2019-07-12 22:08
After some experimentation, it seems to occur once 2FA is enabled for the user. Once that is set, you'll get 500 everywhere.

**Comment by Mohammed90** [comment] 2019-07-14 02:11
The log message after enabling `APP_DEBUG`:
```
(1/1) Decrypt Exception
The payload is invalid.
--
in Encrypter.php line 195
at Encrypter->getJsonPayload(null)in Encrypter.php line 136
at Encrypter->decrypt('[redacted]',  true)in helpers.php line 382
at decrypt('[redacted]')in User.php line 331
at User->getGoogle2faSecretAttribute('[redacted]')in HasAttributes.php line 446
at Model->mutateAttribute('google2fa_secret',   '[redacted]')in HasAttributes.php line 346
at Model->getAttributeValue('google2fa_secret')in HasAttributes.php line 319
at Model->getAttribute('google2fa_secret')in Model.php line 1519
at Model->__get('google2fa_secret')in Google2FA.php line 57
at Google2FA->getGoogle2FASecretKey()in Google2FA.php line 67
at Google2FA->isActivated()in Authenticator.php line 136
at Authenticator->canPassWithoutCheckingOTP()in Authenticator.php line 121
at Authenticator->isAuthenticated()in Middleware.php line 14
at Middleware->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in U2f.php line 57
at U2f->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in WebauthnMiddleware.php line 57
at WebauthnMiddleware->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EnsureEmailIsVerified.php line 23
at EnsureEmailIsVerified->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckCompliance.php line 34
at CheckCompliance->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckVersion.php line 32
at CheckVersion->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 28
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 75
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SentryContext.php line 43
at SentryContext->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 104
at Pipeline->then(object(Closure))in Router.php line 682
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 657
at Router->runRoute(object(Request), object(Route))in Router.php line 623
at Router->dispatchToRoute(object(Request))in Router.php line 612
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 62
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 104
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 52
```

I don't know how sensitive the data passed to decrypt method, so I just redacted it. I can reproduce it consistently anyways.

**Comment by radek-sprta** [comment] 2019-08-04 13:59
I can confirm this issue. I had to disable 2factor in the database as a workaround.

**Comment by asbiin** [comment] 2019-08-09 12:29
Duplicate of #2761

**Closed by asbiin** 2019-08-09 12:29 UTC
