### ISSUE TITLE
things that I borrow, list Debts notes in dashboard

### ISSUE THREAD

**Issue by farconada** [monicahq/monica#3891] opened 2020-04-23 13:55 UTC
I use the Debts feature to write down things I borrow and It's a bit frustrating that I cant personalize the dashboard so you can list the notes next to the contact

Thanks

**Comment by asbiin** [comment] 2020-05-14 15:22
May be a duplicate of #1706

**Comment by asbiin** [comment] 2021-06-27 13:34
duplicate of #1706

**Closed by asbiin** 2021-06-27 13:34 UTC
