### ISSUE TITLE
Missing avatars in autocomplete

### ISSUE THREAD

**Issue by alehkot** [monicahq/monica#2057] opened 2018-11-15 17:22 UTC
Hi,

I found the following issue with avatars in the contact search autocomplete results:

**Steps to reproduce:**

1. Start typing an existing contact first or last name in the top search box
2. Observe avatars in autocomplete results box

**Expected behavior:**
Users avatars are displayed 

**Actual behavior:**
Users avatars aren't displayed

**Additional notes:**

- Users avatars are properly displayed elsewhere
- I'm using self-hosted 2.10.1 version
- Here is the actual HTML workup <img width="782" alt="xnip2018-11-15_12-17-52" src="https://user-images.githubusercontent.com/668169/48569746-8e1e6b80-e8d0-11e8-8967-973adcc17e01.png">

**Comment by allanlw** [comment] 2018-11-16 16:48
I think this is a duplicate of #1985. I'm having the same issue.

**Comment by djaiss** [comment] 2018-11-21 12:45
Sorry about that.
@asbiin has created a fix #2075 and it will be in production soon.

**Closed** 2018-11-24 12:19 UTC
Labels: bug
