### ISSUE TITLE
SSL termination issues

### ISSUE THREAD

**Issue by jwynn6** [monicahq/monica#835] opened 2018-01-20 04:46 UTC
I have a SSL termination/load balancer/reverse proxy that sits in front of Monica.  When trying to enter data, the site now warns that data may be sent insecurely, upon clicking 'ok' the site reloads and nothing is inserted. 

Suggestions?
<img width="478" alt="screen shot 2018-01-19 at 11 45 19 pm" src="https://user-images.githubusercontent.com/6757260/35179942-f6a69636-fd72-11e7-8121-db746c344788.png">

**Comment by degan6** [comment] 2018-01-20 06:10
Interesting, looks like your on a mac but let's start with some other questions. 
What browser are you using?
Do you connect to your reserver proxy over https?

**Comment by t-rascal** [comment] 2018-01-20 14:58
Hello, I am experiencing a similar issue and believe it is related to the closed issue #479. 

I am receiving a warning about an insecure form submission when trying to add a significant other to a contact, and clicking submit then leads to the "Whoops, something went wrong" screen. 

According to issue #479 it's due to use of HTTP calls... The noted work around is to enable HTTPS in the docker container directly. I've been trying to do that but being a docker newbie no luck as of yet (I've never built my own image before - and the base image doesn't include a2enmod so I'm stuck!)

Anyway other info - 
Client browser: tested on both Chrome/Win10, Safari/Mac and Safari/iPhone. 
Host: official MonicaHQ docker image on RancherOS. 
Reverse Proxy: NGINX with SSL termination proxying to HTTP Monica port. 

Please let me know if I can provide any useful logs etc. 

Finally my apologies if this is a separate issue, in which case please disregard the above!

**Comment by jwynn6** [comment] 2018-01-20 22:20
I was on a Mac. I get the same result mobile or on Linux too. Firefox and Chrome. 

Browser ----(https)--- nginx proxy ---- (http)--- Monica

Hope that diagram helps.

On January 19, 2018 10:10:41 PM PST, degan6 <notifications@github.com> wrote:
>Interesting, looks like your on a mac but let's start with some other
>questions. 
>What browser are you using?
>Do you connect to your reserver proxy over https?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/monicahq/monica/issues/835#issuecomment-359148877

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by t-rascal** [comment] 2018-01-22 12:12
Today I experimented by changing the reverse proxy setup as follows:

Browser -----(http) --- nginx proxy ---- (http) --- Monica.

Result: adding significant others and other such form submissions work as expected.

Would still like to resolve the HTTPS issue properly though.

**Comment by realdavidops** [comment] 2018-03-24 19:35
Hey! 

I was having the same issue with my installation in a similar configuration. Here is the fix I had:

**Make sure to set in your .env the APP_ENV to production.** 

Once I did this and restarted my docker container my forms started working.

**Comment by uiharu-s** [comment] 2018-05-27 16:16
Running an instance provisioned with cloudron.io
Getting insecure connection warnings for most form submissions, but data successfully submits if I make an exception.
Cloudron's Monica repo: https://git.cloudron.io/cloudron/monica-app

**Comment by zaroth** [comment] 2018-05-30 08:16
Just writing to say that when running a similar setup to @jwynn6 the suggestion by @realdavidops doesn't work. My `APP_ENV` has been set to `production `all along and I still get "parts of this page are not secure" warning.

**Comment by zaroth** [comment] 2018-05-30 09:03
I can segregate the SSL warnings showed by the browser into two cases (my configuration is an NGINX reverse proxy providing SSL offloading for the docker container made from official image, see more [here](https://github.com/monicahq/monica/issues/1050#issuecomment-393069446)) :

- The avatars hosted by Monica seem to have URLs passed with a `http://` prefix and therefore have to be redirected by the reverse proxy back to HTTPS ([config here](https://github.com/monicahq/monica/issues/1050#issuecomment-393069446)). This results in Firefox showing HTTPS warnings for parts of the website not being encrypted:

![obraz](https://user-images.githubusercontent.com/840021/40709497-7f0c9a72-63f6-11e8-9208-6750cf72499b.png)

![obraz](https://user-images.githubusercontent.com/840021/40709660-f60c6972-63f6-11e8-99e5-ab783e7dabfc.png)

- When submitting `POST `requests (like when confirming adding an activity to a contact) the URLs used are also `http`. This results in this warning shown by Firefox:

![obraz](https://user-images.githubusercontent.com/840021/40710053-edd0e41c-63f7-11e8-9f75-4eee3ea51189.png)

After confirming this dialog, the console log shows (I have `APP_DEBUG=true`):

```
Navigated to http://monica.example.com/activities/store/h:RqMJ9AaZ41GPbOgDp6
```

Which again shows that a `http` link was used for the `POST`.

I wish I could help more with this issue, but my PHP skills are quite lacking. I started digging into how the `getAvatarUrl()` function is implemented in `Contact.php` to see where the rogue `http://` comes from, but I got lost on this line: 

```
 return asset(Storage::disk($this->avatar_location)->url($resized_avatar));
```

This Storage class seems to come from Laravel framework and I was unsure on how to proceed further with my limited knowledge. I'd appreciate some pointers here.

**Comment by djaiss** [comment] 2018-08-10 19:18
Is this still a problem?

**Comment by gramakri** [comment] 2018-09-09 00:03
@djaiss Yeah, this is still an issue (on Cloudron atleast). I am debugging this to find out the root cause.

**Comment by gramakri** [comment] 2018-09-09 07:50
@djaiss @uiharu-s The Cloudron issue is fixed by setting an appropriate value for APP_TRUSTED_PROXIES as suggested in https://github.com/monicahq/monica/issues/1535#issuecomment-415965254

**Comment by tscibilia** [comment] 2018-09-28 03:40
I don't mean to hijack this post but since it's still open, I wanted to add that I'm self-hosting via docker and I'm experiencing the same exact issues. 

Just to note, some of my settings are:
APP_ENV = production, APP_DEBUG = false, APP_TRUSTED_PROXIES = *

I'm using nginx to reverse proxy with a very similar config to @zaroth

**Comment by DanTulovsky** [comment] 2018-10-30 17:30
I also have this issue, although I am using Apache as the reverse proxy to do SSL.


(1/1) MethodNotAllowedHttpException
--
in RouteCollection.php line 255
--
at RouteCollection->methodNotAllowed(array('POST'))in RouteCollection.php line 242
at RouteCollection->getRouteForMethods(object(Request), array('POST'))in RouteCollection.php line 176
at RouteCollection->match(object(Request))in Router.php line 633

....

**Comment by DanTulovsky** [comment] 2018-10-30 18:18
Ok, in my case the problem stems from the fact that a form submission is using 'http' instead of 'https'.  So it sends a request to http://myhost, which gets a 301 redirect, dropping the POST and making it a GET.

It looks like I might be able to fix this by serving a 307 redirect instead, but, why is the form submission using 'http' in this case?

Looking at the page... it looks like everything says http:// ... which I guess works fine for GET requests with a 301 redirect, but not for POST.  I guess monica can always do something like:

<a href="//host.com/>

instead of specifying the protocol.. but my APP_URL says 'https://...', is that no what's used to construct the links?

thank you
dan

**Comment by DanTulovsky** [comment] 2018-10-30 18:28
Ok, changing the redirect on 'http' in apache to a 308 fixed it.  For those using mod_rewrite:

        RewriteEngine on
        RewriteCond %{SERVER_NAME} =monica.mydomain.com
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,NE,R=308]

is what works for me.

**Comment by allanlw** [comment] 2018-11-13 23:46
With #1997 getting merged, I think this can probably get closed.

@DanTulovsky Take a look at https://github.com/monicahq/monica/blob/master/docs/installation/ssl.md

**Comment by DanTulovsky** [comment] 2018-11-14 00:37
Ah, thank you. For apache, adding:

RequestHeader add X-Forwarded-Proto https

made the links show up as 'https'.

**Comment by FranPregernik** [comment] 2019-02-02 14:06
Hi,

I managed to get this working on my setup:
```
Browser ---(https)--- nginx proxy ---(http)--- (official docker image) Apache+Monica
```

in nginx i have this location block:
```nginx
        location / {
                proxy_pass  http://127.0.0.1:7777;
                proxy_request_buffering         off;
                proxy_redirect                  off;
                proxy_set_header                Host $host;
                proxy_set_header                X-Real-IP $remote_addr;
                proxy_set_header                X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header                X-Forwarded-Host $server_name;
                proxy_set_header                X-Forwarded-Proto $scheme;
        }
```

The login page would load over https but the browser would flag it insecure and all the URLs to css and the form post were http.

I also have the correct env setup:
```
APP_ENV=production
APP_URL=https://example.com
```

I know https://github.com/monicahq/monica/blob/f660c4fd98bd7aa70d4cd5af865efc3352a38aee/app/Providers/RouteServiceProvider.php#L67 has the switch to force the schema to https when APP_ENV=production BUT I had to change the app/Providers/AppServiceProvider.php file and add the same check in the boot method to get the login screen to work. Here is my AppServiceProvider.php file as it is now (for completeness): 
```php
<?php

namespace App\Providers;

use App\Helpers\DBHelper;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\App;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        View::composer(
            'partials.components.currency-select', 'App\Http\ViewComposers\CurrencySelectViewComposer'
        );

        View::composer(
            'partials.components.date-select', 'App\Http\ViewComposers\DateSelectViewComposer'
        );

        View::composer(
            'partials.check', 'App\Http\ViewComposers\InstanceViewComposer'
        );

        if (config('database.use_utf8mb4')
            && DB::connection()->getDriverName() == 'mysql'
            && ! DBHelper::testVersion('5.7.7')) {
            Schema::defaultStringLength(191);
        }

        if (App::environment('production')) {
            URL::forceScheme('https');
        }
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
    }
}
```

When the user is not authenticated it seems RouteServiceProvider::boot is never invoked. 

@djaiss  I am not sure if this is the correct place to put it so I won't make a PR but I think it is enough to point a maintainer int the right direction.

Best regards,
Fran

**Comment by FranPregernik** [comment] 2019-02-14 04:48
Update to my last comment.

After upgrading to the new version 2.12.0 I had to apply my patch.
This time I moved the IF/forceSchema block to the top of the `boot` method of `monica/app/Providers/RouteServiceProvider.php` instead of the AppServiceProvider.

After this HTTPS is working like a charm.

Can we please merge this in the mainline? 

Best regards,
Fran

**Comment by asbiin** [comment] 2019-02-14 07:56
@FranPregernik you are welcome to open a Pull Request for this change, this can help us! Thank you.

**Comment by FranPregernik** [comment] 2019-02-14 08:39
@asbiin Will do..

**Comment by asbiin** [comment] 2019-05-17 05:13
Fixed

**Closed by asbiin** 2019-05-17 05:13 UTC
Labels: help wanted, packaging, support
