### ISSUE TITLE
Show contacts in Map View

### ISSUE THREAD

**Issue by stacksjb** [monicahq/monica#4826] opened 2021-01-27 20:24 UTC
I would like to be able to view where my contacts are from a Map view

**Describe the solution you'd like**
I would like to be able to view all of my contacts (with location information) in a map view.
While you can currently view contact information on a map individually, you can't view them collectively in a single map view

**Additional context**
It would be useful and neat to be able to see everyone in a map view. Probably the biggest use case is if I am doing something that is location specific (such as visiting a specific location) I can easily browse from that context and see who is nearby.

**Comment by asbiin** [comment] 2021-01-30 14:34
That's a great idea, and this is a duplicate of #391

**Closed by asbiin** 2021-01-30 14:34 UTC
