### ISSUE TITLE
Infer relationships (i.e. transitive relationships)

### ISSUE THREAD

**Issue by casidiablo** [monicahq/monica#2467] opened 2019-02-22 20:36 UTC
I think it's very tiresome to configure every relationship between all your contacts, and some are very redundant.

For instance, let's say I have Alice, Bob, Charlie, and Duncan.

- Alice is Charlie's mother
- Bob is Charlie's father
- Alice is Duncan's mother
- Bob is Duncan's father

Why do I have to explicitly tell Monica that Charlie and Duncan are siblings?

If I add Evan as Duncan's son... why do I have to explicitly tell Monica that Alice and Bob are his grandparents?

**Comment by trwnh** [comment] 2019-02-22 21:17
Related: #1255 #1327 
Possible duplicate of #357

**Comment by asbiin** [comment] 2019-08-11 20:37
This is a duplicate of #1255

**Closed by asbiin** 2019-08-11 20:37 UTC
