### ISSUE TITLE
Reminder date differs from the date that's in the database by one day

### ISSUE THREAD

**Issue by sid3windr** [monicahq/monica#3599] opened 2020-02-18 20:20 UTC
The reminder for Feb 29th is set to March 1st. This is probably 'normal' except during leap years you don't really want to be a day late.

![image](https://user-images.githubusercontent.com/1889999/74774670-70d70a80-5294-11ea-9693-76215baec97e.png)

I would suggest reminders and such are really set for the 29th, and on non-leap years, are processed as well on March 1st.

**Comment by daryljones** [comment] 2020-02-19 05:41
I'm seeing issues with date of birth display unrelated to Deb 29th.  PHP timezone is set correctly.  The display date often differs from the date that's in the database by one day. (Built from source with a pull from today's master.)

**Comment by asbiin** [comment] 2020-02-29 18:21
@daryljones is right, I have renamed the bug.

**Comment by sid3windr** [comment] 2020-02-29 20:19
Hah, okay - I didn't check that far, probably because I don't know most people's birthdays by heart :D Just saw the 29/2 ones that were definitely wrong. Thanks for checking/updating.

**Comment by daryljones** [comment] 2020-03-12 04:51
Thanks for your work on the date issue.  Seems to be much better with carbon-2.

**Comment by asbiin** [comment] 2021-10-17 19:03
duplicate of #887

**Closed by asbiin** 2021-10-17 19:03 UTC
Labels: bug
