### ISSUE TITLE
"Date you met" defaults to today upon edit, even if "I don't know" was selected previously

### ISSUE THREAD

**Issue by GjjvdBurg** [monicahq/monica#1927] opened 2018-10-19 19:10 UTC
Thanks for a great project!

**Describe the bug**
1. For a contact, click "add" under the "How You Met" section
2. Add description, and select "I don't know the date we met", click Save.
3. Now click "edit" under the "How You Met" section. The radio button under "Date you met" is on today's date again.

This is confusing, since I shouldn't have to reset the radio button to a previously selected choice on editing.

**Which version are you using:**
 - A server I maintain myself, version 2.9.0

**Comment by mechanarchy** [comment] 2019-02-25 07:31
This is still present in 2.12.0. I've had a look through the code for this and it seems there's a couple of reasons:
* `resources/views/people/introductions/edit.blade.php` expects a property `$contact->first_met` that no longer appears to exist. I've done a workaround for this but it didn't fix the problem described above.
* Even when the generated HTML is correct (ie, `checked` attribute set as intended), as soon as the JavaScript code runs it overrides the value. I believe this is because `resources/assets/js/app.js:341` sets `date_met_the_contact: 'known'` at a global level. I don't know enough about Vue yet to resolve this. 

It looks like most of the global-level properties are used by `.blade.php` style files and the `.vue` files have local state - so perhaps rewriting this page into the `.vue` style entirely will fix it and will make it more consistent with the majority of the codebase.

**Comment by jcassee** [comment] 2021-05-24 20:20
I'm going through good first issues, but this one seems to be fixed by #4511? Should it be closed or is there more to it?

**Comment by GjjvdBurg** [comment] 2021-05-24 20:32
I haven't used Monica in a while, so I can't confirm from experience. However, as #4511 seems to directly target this bug, I'd guess it was fixed and this can be closed.

**Closed** 2021-08-16 14:15 UTC
Labels: bug, good first issue
