### ISSUE TITLE
Remove compiled assets from repository

### ISSUE THREAD

**Issue by tomzx** [monicahq/monica#800] opened 2018-01-13 18:49 UTC
Hello,

Is there a reason that compiled assets (`public/css/app.css`, `public/js/app.js`) as well as some fetched assets (`public/fonts/vendor/font-awesome/fontawesome-webfont.svg`, 
`public/fonts/vendor/octicons/build/octicons.svg`) part of the repository? As they are either compiled or fetched when you install/update monica, there is no reason those should be part of the repository and they should actually be included in the `.gitignore`.

Thoughts?

**Comment by djaiss** [comment] 2018-01-14 17:07
@tomzx technically they are not necessarily compiled if you install Monica, both locally or on a server. They just are if you run `npm run dev` or `npm run prod`. If we remove the compiled assets, we would force people to install node etc... while at the moment, they don't have to if they don't want to.

I think it's simpler that way. Moreover, it's also simpler for me so I don't need to compile them on the server 😀 But I'm open to the debate here.

**Comment by tomzx** [comment] 2018-01-14 18:41
The issue is that the git repository now contains those files and they are large, ~3MB for `app.css` and ~5MB for `app.js`. Now, I'm not complaining about the size in itself, as text is highly compressible, but it's generally a best practice not to commit anything that is generated.

If we want to make it easy for people to run it without requiring `npm`/`yarn`, then a better alternative would be to prepare a ready-to-use archive.

Finally, it begs the question "when should these files be commited?" Should they be only updated by the person preparing a release, or by anyone that modifies a file that will end up in `app.css`/`app.js`, or are they just updated "when someone feels like it"?

**Comment by djaiss** [comment] 2018-01-14 18:43
I agree that the current state of the repository is not clean. I hate having generated files inside git.

I think we should move forward with removing them from the repository and I would have to compile them on the server after each pull. I just need to figure out how 😀

**Comment by tomzx** [comment] 2018-01-14 18:48
Given that you use laravel, you could consider using [envoy](https://laravel.com/docs/5.5/envoy) to script your deployment. Or you could write a php script or a node.js script and call that after `git pull`.

**Comment by djaiss** [comment] 2018-01-14 23:35
@tomzx oh that's nice! I thought it was only available to the Envoyer subscribers!
Thanks for the reco, I'll check it out.

**Comment by asbiin** [comment] 2018-03-20 17:26
This is a duplicate of #136

**Closed by asbiin** 2018-03-20 17:26 UTC
