### ISSUE TITLE
add comment field for uploaded photos/pictures

### ISSUE THREAD

**Issue by hugofant** [monicahq/monica#3433] opened 2020-01-05 18:17 UTC
hi,
i'm new to monicahq and i really like it.
Only feature missing (acutally) is the possibility to comment the uploaded pictures (for example - when uploading pictures from the kids it would be great to combine them with their names in a textfield.

**Comment by elanosilveira** [comment] 2020-01-06 17:03
related to #3319

**Comment by asbiin** [comment] 2020-02-29 18:29
duplicate of #3319

**Closed by asbiin** 2020-02-29 18:29 UTC
