### ISSUE TITLE
Cannot delete contact when using a DB prefix

### ISSUE THREAD

**Issue by robwent** [monicahq/monica#2321] opened 2019-01-20 23:44 UTC
On a fresh install, I seem to be able to do everything other than delete a contact (Seemed to get a duplicate after changing the first name of an existing contact).

Self-hosted
Ubuntu 18.04
Tag 2.11.2

User has full database privileges.

The error logs look like the prefix is being added twice when trying to perform a select query which throws the fatal error.

I've changed the db/user and prefix but the error is this:

```SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'MYUSER'@'localhost' for table 'tables' (SQL: select `table_name` from `mon_mon_information_schema`.`tables` where `table_schema` = MYDB)```

I've had a search through the code but I'm not sure where the delete action is called and I can't see anything where the prefix is manually added.

**Comment by robwent** [comment] 2019-01-20 23:47
Or maybe the issue is that the prefix shouldn't be added to infrmation_schem at all since it's not an app specific table that uses the prefix?

**Comment by robwent** [comment] 2019-01-20 23:51
Seems to be related to this issue https://laravel.io/forum/03-20-2014-override-table-prefix-for-one-model

And the issue being here: https://github.com/monicahq/monica/blob/master/app/Helpers/DBHelper.php#L40

**Comment by robwent** [comment] 2019-01-21 00:14
I don't have the Laravel knowledge to fix this, but I can confirm that manually removing the prefix from all tables and the .env file lets me delete contacts.

I also got an error on install which may also have been related.
Running the API command mentioned in the docs also creates tables without a prefix.

**Comment by asbiin** [comment] 2019-05-17 04:50
Duplicate of #1896

**Comment by robwent** [comment] 2019-05-17 10:06
Although they are the same issue, doesn't this provide more detail about the problem?

**Closed** 2019-08-30 22:16 UTC
Labels: bug
