### ISSUE TITLE
When Editing Activity - category does not correctly populate

### ISSUE THREAD

**Issue by cstrat** [monicahq/monica#5413] opened 2021-08-06 04:59 UTC
**Describe the bug**
When adding an activity I can select a category for that activity.
When editing that same activity, the form re-populates everything to be edited - however the category does not re-populate.
This does not cause an issue when you save (it doesn't over-write the category) - so appears cosmetic only.
See screenshots below.

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.
Step 1, create activity:
![image](https://user-images.githubusercontent.com/4209076/128458110-734cdc0f-ee66-4487-b83a-350a89ed3ad5.png)

Step 2, save, all correct:
![image](https://user-images.githubusercontent.com/4209076/128458135-efc5d6b1-16ce-488d-b997-0abc75276fa4.png)

Step 3, click edit activity. (notice category is 'just hung out')
![image](https://user-images.githubusercontent.com/4209076/128458155-d535490b-a3cf-4596-aefb-f5f13ff05222.png)

Now if I don't edit anything and click save, it is still saved as 'picnicked'.
If I change the category and click save, it does update it, so thats good.

So this is just a UI issue when loading that edit form.

**Which version are you using:**
 - Self Hosted
 - v3.1.3

**Comment by tarator** [comment] 2021-08-06 11:14
I think this only happens, when editing an previously saved Activity **AND** not changing other fields like "What did you do with...?" or the field of "Add more details"

**Comment by cstrat** [comment] 2021-08-06 11:24
This happens to me anytime I edit an activity where I've previously set the category. The edit form never loads with the correct value.

> Yes, but it's problematic if I just want to change the activity explicitly to "just hung out". Pressing the save button will not change the category in to "just hung out" in that case.

I mean that is a problem, but the UI should properly reflect the actual value.

**Comment by asbiin** [comment] 2021-10-02 08:49
duplicate of #5392

**Closed by asbiin** 2021-10-02 08:49 UTC
Labels: bug
