### ISSUE TITLE
can search extra info, for examples tags, activities .

### ISSUE THREAD

**Issue by materliu** [monicahq/monica#3068] opened 2019-10-05 03:27 UTC
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex.
* I'm always frustrated when [...]
* Current feature X is awesome but doesn't fill the need of [...]
* Monica doesn't have feature X which is essential as [...]

**Describe the solution you'd like**

**Describe alternatives you've considered (optional)**

**Additional context**
Add any other context or screenshots about the feature request here. The more context, the better.

**Comment by asbiin** [comment] 2019-10-20 20:22
This is a duplicate of #2590

**Closed by asbiin** 2019-10-20 20:22 UTC
