### ISSUE TITLE
Let us add custom "Features"

### ISSUE THREAD

**Issue by b3nd1k** [monicahq/monica#5773] opened 2021-12-19 15:12 UTC
Hey! I would like to be able to add custom features, just not hide the existing ones. I would like to be able to add fields such as "Faith" for religion, Zodiac Sign, Personality Type and so on.

**Comment by asbiin** [comment] 2022-01-02 21:50
this is a duplicate of #79

**Closed by asbiin** 2022-01-02 21:50 UTC
Labels: feature request
