### ISSUE TITLE
Can't use monica without SSL anymore

### ISSUE THREAD

**Issue by croesch** [monicahq/monica#2519] opened 2019-03-12 23:26 UTC
**Until 2.12.1**
I have a local instance of monica running and it doesn't use https. I set `APP_URL=http://myserver.router.domain/` and `APP_ENV=production` and I can login and work without using SSL.

**With 2.12.1**
Now with `2.12.1` monica enforces SSL and even the login screen tries to load resources from https. This breaks my setup until SSL is running.

I guess #2439 is the reason for that behavior.

**Solution**
Is it acceptable for you to support `APP_ENV=production` and `APP_URL` with scheme `http` without SSL? Or do you want to enforce SSL? If you want to enforce SSL it would still be nice to not hide it as a _bug fix_. That was my second update of monica and the second time I ran into an issue.. sorry if I sound disappointed, I'm really happy about monica and what you did so far :+1: 

Where can I read what else will changes if I set `APP_ENV=local`? Will monica still have all features, like notifications and stuff? Or will it turn into a `development` mode app which will not send any messages?

**Comment by ein-stein-chen** [comment] 2019-03-13 13:13
Duplicate of #176 

Comment of djaiss (State: 13 Jun 2017)
> [...] currently, `APP_ENV` is used for very few cases:
>     * check if it needs to load JS scripts (Intercom, GA)
>     * Seeders for fake data
>     * PHPunit

It would be a good idea to pursue the idea of adding an ENV variable to indicate whether we want to enforce HTTPS or not.

**Comment by croesch** [comment] 2019-03-14 08:09
Thanks, I didn't notice any redirects mentioned in #176 with `2.12.0` and the previous version.

Also I agree that you may not want to support HTTP-only as it depends on the setup whether it's secure or not.

But certainly I'd like having it more explicit whether or not HTTPS is forced.

**Comment by MarkNBroadhead** [comment] 2019-03-15 01:31
Yeah, this newest update completely broke my internally hosted solution. Updated to 2.12.1 and it broke. I have monicahq hosted on docker behind [nginx-proxy](https://github.com/jwilder/nginx-proxy). 
This is hosted in a private network. I do not need SSL as I only access via VPN.

**Comment by cristobaltapia** [comment] 2019-04-11 20:59
Is there any solution to this? I tried to configure SSL according to [this](https://github.com/monicahq/monica/blob/master/docs/installation/ssl.md) doc, but it does not work. I am running it on my home server using docker.

**Comment by ein-stein-chen** [comment] 2019-04-14 16:42
The solution for hosting Monica in a private network without SSL is setting `APP_ENV` to `local` or in any case not to `production`.

**Comment by cristobaltapia** [comment] 2019-04-14 18:38
Thanks for that! That works for me. I am not an expert in SSL certificates and was getting a bit frustrated trying to configure this without success. But now, everything is back to normal :)

**Closed** 2019-05-17 05:17 UTC

**Comment by sajanp** [comment] 2020-11-09 00:44
Just wanted to come here to say as a brand new user of the app, I did my first install and encountered this issue.  Checked NGINX, checked my .env, I'm very familiar with Laravel and there was no indication that at the app level SSL was required.

Leave SSL and HTTP/TLS stuff where it belongs, at the web server level.  The app layer itself should not force me into SSL.
