### ISSUE TITLE
Relationships should be People entities too

### ISSUE THREAD

**Issue by jbrooksuk** [monicahq/monica#103] opened 2017-06-07 16:53 UTC
For example, I'm friends with someone and their significant other, so I should be able to existing people together.

Likewise, kids should be a manageable person. Other relationships could include:

- Brother, Sister
- Parent
- Uncle/Auntie
- Grand-parent
- Niece/Nephew

**Comment by adrum** [comment] 2017-06-07 17:25
Dupe of probably #19, #35, and #41

**Comment by jbrooksuk** [comment] 2017-06-07 17:32
My search didn't do a good job. Thanks

**Closed** 2017-06-07 17:32 UTC
