### ISSUE TITLE
Inherit family relations from other relations

### ISSUE THREAD

**Issue by simonszu** [monicahq/monica#2382] opened 2019-02-04 13:43 UTC
It would be great if monica could inherit implicit family relations, e.g. 
- if two people have the same father and mother, they are automatically noted as siblings
- if they have only one same parent, they are noted as half-siblings
- if they have the same child, monica should suggest their relations (one-night-stand, spouse, or just boy/girlfriend, at least "had sex" or something)

You could even expand the logic, for grandchildren, or cousins. I have no idea how far this expansion could be practical, but it is a base for discussions.

**Comment by OrinSafko** [comment] 2019-02-04 20:49
Interesting to see this posted today as I had some frustration this morning that a feature like this would have mitigated.

I went to my in-laws for the Super Bowl last night. I wanted to log an activity with all of the family members there.

My wife and I were there as well as my in-laws and our nephew. My in-laws are his grandparents. No one existed as contacts yet this morning (except my wife and I).

I added my nephew, father in law, and mother in law into Monica. I had to tell Monica that our nephew was our nephew. Then I told Monica that my in laws are my wife's parents. It would have been magical if Monica automatically listed our nephew as my in laws grandson. However, how would Monica know that my wife's parents are his grandparents? His grandparents could be my parents. Monica wouldn't be able to pick automatically. But if it had prompted, that would have been neat.

Also, I had to list our nephew as my nephew in my contact as well as in my wife's contact. We're listed as each other's spouse. If he's my nephew then it would be logical that he would also be my wife's nephew. Are there family instances where this wouldn't always be the case?

I could see the build out of this being extremely taxing. I'm not a software developer, but thinking through all of the logic has my head spinning.

**Comment by simonszu** [comment] 2019-02-04 21:02
> how would Monica know that my wife's parents are his grandparents?

A differentiation between bloodline and in-law could be neat. But, where do you draw the line between a personal CRM like Monica and a full-blown heritage software like, e.g. Webtrees?

However, there is a standard format for heritage relations, GEDCOM. It is also text-based like vCard.

I'm just thinking, but an import/export feature would be nice. I am maintaining a heritage tree for my family with Webtrees and maintaining a second one with Monica would be redundant work.

Also Monica acting as a carddav server... But I think that's another issue. ;)

**Comment by redlukas** [comment] 2019-08-03 15:01
this would be awesome. But i think it would be helpful to have inferred relationships tagged as such, and then you can click on the tag and either confirm or dismiss the relationship.

**Comment by asbiin** [comment] 2020-05-14 16:44
duplicate of #1255

**Closed by asbiin** 2020-05-14 16:44 UTC
Labels: feature request
