### ISSUE TITLE
Self-hosted instance run with docker-compose is not autopopulating user table

### ISSUE THREAD

**Issue by fmakowski** [monicahq/monica#575] opened 2017-09-04 14:16 UTC
Hello everyone,

I am trying to setup an instance of Monica by using your Docker image. It appears that after I build it and run it (by using docker-compose), it does not have any user entries, so I cannot login. Is there any way of dealing with this?

Best regards,
Filip

**Comment by djaiss** [comment] 2017-09-04 17:01
You can simply register with a new account and you are ready to go.

**Comment by fmakowski** [comment] 2017-09-04 17:04
@djaiss, thanks for the response. I have handled it by exporting my account from instance hosted on monicahq.com and then import it along with contacts and other stuff - and now it works just fine. 

What is kind of weird, is that dashboard is not working in my self-hosted instance (`Whoops, looks like something went wrong.` on top of the site, only on `/dashboard`) - but otherwise, everything works just fine.

Anyway, thanks for great app! I will consider donating either in money or in code ;)

Best regards!
Filip

**Comment by djaiss** [comment] 2017-09-04 18:10
Thanks for your comment! Wonder why you get the error though...

**Comment by fmakowski** [comment] 2017-09-04 19:26
Ok, so I turned on debug mode and started from scratch. This is the exception that can be seen:


    (1/1) UnexpectedValueExceptionThe stream or file "/var/www/monica/storage/logs/laravel-2017-09-04.log" could not be opened: failed to open stream: Permission denied

I tried mapping /var/www/monica/storage/logs to ./persist/storage/logs and it seems, that the file is created with unsufficient permissions for the app:

    -rw-r--r-- 1 root root 3,6K 09-04 21:18 laravel-2017-09-04.log

I am not sure how I can deal with the fact, that everything in `./persistent` is owned by `root`, but regardless of that, docker seems not to be able to write to the file.

Best regards!
Filip

**Comment by fmakowski** [comment] 2017-09-04 19:29
Also, when trying to export SQL file, this is what I encounter:


    (1/1) ExceptionImpossible to create the root directory "/var/www/monica/storage/app/public/exports".

Might be overall permission problem, or my particular misconfiguration. What do you think?

Best regards,
Filip

**Comment by djaiss** [comment] 2017-09-05 15:40
The thing is, we have many Docker installations out there. So I assume this is your configuration, otherwise this kind of issues would have been surfaced already. However I'm really not good at debugging this kind of devops problems :-( Hope the community can help there.

**Comment by jamrizzi** [comment] 2017-11-13 07:03
Try deleting the laravel.log file. The system automatically created a new one with the right permissions.

**Comment by asbiin** [comment] 2018-03-20 17:20
@fmakowski  is it still happening ?

**Comment by abmurksi** [comment] 2019-01-31 18:10
The issue appears if you do not use a docker volume but bind mount a folder and running docker on the host as a non-root user. In that case the container creates the Laravel Log-File as user root on the host (as this is the process that is creating the file within the container) resulting in no access for the Docker-Daemon on the host machine as this is running with the privileges of the non-root user.

See Dockerfile: ENTRYPOINT ["make", "-f", "/var/www/monica/scripts/docker/Makefile"] is run by USER root.

Deleting the log file does not work as it is recreated by the root user in the container again with root permissions, resulting in the same permission issue.

I do not know Laravel enough to see where the logging is triggered but maybe this helps in resolving the issue?
We should try to avoid using the root user but use the already existing monica user somehow.

**Comment by ruubje11** [comment] 2019-06-11 22:00
Did anyone get any progress on this? Got the same issue now

**Comment by hugofant** [comment] 2020-01-08 10:22
Hi,
I'm actually struggling with the same problem, and as in the meantime some time has passed, i want to ask, if there's alread a solution for it.

**Comment by hugofant** [comment] 2020-01-09 08:31
short additional info: docker image "JC5/monica-multi-arch" is working well (tested on X86).

**Comment by asbiin** [comment] 2020-01-09 12:00
I'm not aware of the image you're talking about.

I don't see where this could come from. The official docker image is working normally ...

**Comment by hugofant** [comment] 2020-01-09 15:46
Hi,
the problem shows with image "monicahq/monicahq"...which is the official one....

**Comment by asbiin** [comment] 2020-01-09 17:53
Well, I don't see what the problem is really ...
I have a docker instance, and it's working well, can you explain what is the issue here?

**Comment by hugofant** [comment] 2020-01-11 15:34
after a complete fresh installation of docker and monicahq container i'm not able to reproduce the problem, so problems seems to be nonrecurring and i want to excuse myself  for causing  inconveniences.

**Closed** 2020-01-11 19:32 UTC
Labels: packaging
